"""ammar -- the maintenance queue every tower refills by 9am."""

import argparse
import os
import sys
from datetime import date, datetime

from . import agents, report, rules, technicians, tickets
from .config import Config


def build_parser():
    p = argparse.ArgumentParser(
        prog="ammar",
        description="Tower maintenance dispatch: urgency scoring and "
                    "completion-integrity checks are computed, never "
                    "generated by a model. A completion record that fails "
                    "the integrity check reopens automatically with no "
                    "model call at all.",
    )
    p.add_argument("tickets", help="maintenance ticket queue CSV")
    p.add_argument("--technicians", default=None,
                   help="technician roster CSV (default: alongside the "
                        "tickets file, named technicians.csv)")
    p.add_argument("-o", "--out", default="closures.csv", help="closure CSV")
    p.add_argument("--config", default=None, help="JSON overriding policy thresholds")
    p.add_argument("--today", default=None, help="YYYY-MM-DD, for reproducible runs")
    p.add_argument("--show-low", action="store_true",
                   help="list low-band tickets too (logged, not queued)")
    p.add_argument("--no-agents", action="store_true",
                   help="computed queue only; no model calls")
    p.add_argument("--fail-on", default="none",
                   choices=("none", "suspicious", "reopened"),
                   help="exit non-zero at this state (for a scheduled run)")
    p.add_argument("--no-colour", action="store_true")
    return p


def build_tasks(queue):
    """One task per work order the pipeline needs to write an account for.

    A suspicious completion is pre-reopened here, deterministically -- it
    never reaches a model, because there is nothing for an agent to add to
    a completion record that already fails on its face.
    """
    tasks = []
    for w in queue.work_orders:
        if not w.has_completion:
            continue
        if w.suspicious:
            tasks.append({
                "ticket_id": w.ticket_id,
                "label": f"{w.category} ticket in {w.tower}/{w.unit}",
                "facts": w.facts(),
                "allowed": agents.expand_evidence(w.facts()),
                "status": "reopened",
                "status_reason": f"deterministic completion-integrity check "
                                 f"failed -- no model call needed: {w.suspicious_reason}",
            })
        else:
            tasks.append({
                "ticket_id": w.ticket_id,
                "label": f"{w.category} ticket in {w.tower}/{w.unit} "
                         f"({w.band}, {w.urgency_points} points)",
                "facts": w.facts(),
                "allowed": agents.expand_evidence(w.facts()),
            })
    return tasks


def main(argv=None):
    args = build_parser().parse_args(argv)

    today = date.today()
    if args.today:
        try:
            today = datetime.strptime(args.today, "%Y-%m-%d").date()
        except ValueError:
            print(f"ammar: --today must be YYYY-MM-DD, got {args.today}",
                  file=sys.stderr)
            return 2

    try:
        cfg = Config.load(args.config)
    except (OSError, ValueError) as exc:
        print(f"ammar: config: {exc}", file=sys.stderr)
        return 2

    if not os.path.isfile(args.tickets):
        print(f"ammar: {args.tickets} not found", file=sys.stderr)
        return 2

    tech_path = args.technicians or os.path.join(
        os.path.dirname(os.path.abspath(args.tickets)), "technicians.csv")
    if not os.path.isfile(tech_path):
        print(f"ammar: {tech_path} not found -- pass --technicians", file=sys.stderr)
        return 2

    try:
        loaded_tickets = tickets.load(args.tickets)
        loaded_techs = technicians.load(tech_path)
    except (OSError, ValueError) as exc:
        print(f"ammar: {exc}", file=sys.stderr)
        return 2

    queue = rules.assess(loaded_tickets, loaded_techs, cfg, today)

    all_tasks = build_tasks(queue)
    pre_reopened = [t for t in all_tasks if t.get("status") == "reopened"]
    to_review = [t for t in all_tasks if "status" not in t]

    agentic = not args.no_agents and bool(to_review)
    if agentic:
        try:
            to_review = agents.run(to_review)
        except agents.AgentUnavailable as exc:
            print(f"ammar: {exc}", file=sys.stderr)
            print("ammar: falling back to the computed queue.", file=sys.stderr)
            agentic = False

    if agentic:
        for t in to_review:
            agents.gate(t, t["allowed"])
        review_tasks = pre_reopened + to_review
    else:
        review_tasks = pre_reopened

    print(report.terminal(queue, cfg, agentic, review_tasks,
                          use_colour=not args.no_colour, show_low=args.show_low))

    report.write_csv(args.out, queue, review_tasks)
    print(f"  closures -> {args.out}")
    print("")

    suspicious = [w for w in queue.work_orders if w.suspicious]
    if args.fail_on == "suspicious" and suspicious:
        return 1
    if args.fail_on == "reopened" and any(t.get("status") == "reopened" for t in review_tasks):
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
